site_name: Metricheq
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
nav:
  - Home: index.md
  - Connectors:
      - GitHub: connectors/github.md
      - Pagerduty: connectors/pagerduty.md
      - Sonar: connectors/sonar.md
      - Prometheus: connectors/prometheus.md