name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  quality:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Format with ruff
      run: |
        poetry run ruff format .

    - name: Lint with ruff
      run: |
        poetry run ruff check .

    - name: Type check with mypy and install missing type stubs using Poetry
      run: |
          poetry run mypy . || true
          poetry run mypy --install-types --non-interactive
          poetry run mypy .
          
    - name: Test with unittest
      run: |
        poetry run coverage run -m unittest discover -v
        poetry run coverage xml 
        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
